### This file is generated by opam2nix.

self:
let
    lib = self.lib;
    pkgs = self.pkgs;
    selection = self.selection;
    repoPath = self.repoPath;
    repos = 
    {
      opam-repository = 
      rec {
        fetch = 
        {
          owner = "ocaml";
          repo = "opam-repository";
          rev = "aef07c8faffdc0a34b1e4297f74a5003c6c4f434";
          sha256 = "1fw59qgp37yxm29vds41sx44z49w23z5xkhjzy3a2zglj0884v84";
        };
        src = (pkgs.fetchFromGitHub) fetch;
      };
    };
in
{
  format-version = 4;
  inherit repos;
  ocaml-version = "4.14.1";
  selection = 
  {
    astring = 
    {
      pname = "astring";
      version = "0.8.5";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/astring/releases/astring-0.8.5.tbz";
        sha256 = "1ykhg9gd3iy7zsgyiy2p9b1wkpqg9irw5pvcqs3sphq71iir4ml6";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/astring/astring.0.8.5";
        hash = "sha256:1djnad9sq12idlakj069xvwm2nn7wqm137pqbxxai5frkgi08x74";
      };
    };
    base = 
    {
      pname = "base";
      version = "v0.16.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/base/archive/refs/tags/v0.16.3.tar.gz";
        sha256 = "0g7rrwnd3sb4pcpnvq7hc7dd7rg1gh0axxdhqwjh60dxw81ybycv";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune-configurator dune conf-bash;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base/base.v0.16.3";
        hash = "sha256:1c6rb2y89zwdp29arlhdmp78hyiwbm335y7yyxmxyh3iq257kak7";
      };
    };
    base-bytes = 
    {
      pname = "base-bytes";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-bytes/base-bytes.base";
        hash = "sha256:0a68lmbf68jgm1i3b59j2sc3ha9yhv4678f9mfwwvczw88prq7l3";
      };
    };
    base-threads = 
    {
      pname = "base-threads";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-threads/base-threads.base";
        hash = "sha256:1c4bpyh61ampjgk5yh3inrgcpf1z1xv0pshn54ycmpn4dyzv0p2x";
      };
    };
    base-unix = 
    {
      pname = "base-unix";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-unix/base-unix.base";
        hash = "sha256:0mpsvb7684g723ylngryh15aqxg3blb7hgmq2fsqjyppr36iyzwg";
      };
    };
    camlp-streams = 
    {
      pname = "camlp-streams";
      version = "5.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/camlp-streams/archive/v5.0.1.tar.gz";
        sha256 = "196rn0z2q53f8is5bwln1n5qzipn5bg3wnflnmzlxfz90qjgcwdd";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/camlp-streams/camlp-streams.5.0.1";
        hash = "sha256:177a68cgm23pryyji88dvn300qz55sl154wfwmzvp8arhs7yg6bn";
      };
    };
    cmdliner = 
    {
      pname = "cmdliner";
      version = "1.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/cmdliner/releases/cmdliner-1.2.0.tbz";
        sha256 = "0y00vnlk3nim8bh4gvimdpg71gp22z3b35sfyvb4yf98j1c11vdg";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cmdliner/cmdliner.1.2.0";
        hash = "sha256:0q1n1rg7pg34h75k02dmfpcwnhcih1hxaiifzi99ac9yhz6k4wg4";
      };
    };
    conf-bash = 
    {
      pname = "conf-bash";
      version = "1";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-bash/conf-bash.1";
        hash = "sha256:1azbsribx7l6x6l06zicp00vmvg24ng54qn42d7a34apj4qvya3h";
      };
      buildInputs = [ (pkgs.bash or null) ];
    };
    conf-python-3 = 
    {
      pname = "conf-python-3";
      version = "9.0.0";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-python-3/conf-python-3.9.0.0";
        hash = "sha256:03gbdbwmy3bax7q81dbanfy6mxsmnz05ky7h2qm1g5gjmm8i2bvl";
      };
      buildInputs = [ (pkgs.python3) ];
    };
    cppo = 
    {
      pname = "cppo";
      version = "1.6.9";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/cppo/archive/v1.6.9.tar.gz";
        sha256 = "0sm2vn5y7w7fyrwkv7f86y4nvs5vsrqy1x2nidy0lcqxq62ns0qn";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cppo/cppo.1.6.9";
        hash = "sha256:19i6yqv9lq09v3xw1sfqayh40sihhd4hfyvk9dwz1m5dv1g63xlp";
      };
    };
    crunch = 
    {
      pname = "crunch";
      version = "3.3.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-crunch/releases/download/v3.3.1/crunch-3.3.1.tbz";
        sha256 = "0spdm3znj6r705sd86lcz31qfx2aqjvaykms3irvgjqb27aa0nrc";
      };
      opamInputs = 
      {
        inherit (selection) ptime ocaml dune cmdliner;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/crunch/crunch.3.3.1";
        hash = "sha256:04zkajphh0yybhpcp7sw16h0wpmmgjx3gbs7rwq70il6hsj7p6aw";
      };
    };
    csexp = 
    {
      pname = "csexp";
      version = "1.5.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/csexp/releases/download/1.5.2/csexp-1.5.2.tbz";
        sha256 = "1zw7fxlhx5mnf09mrhzk0yf3m4bpiii51194j0cs8ya3pc2ds50s";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/csexp/csexp.1.5.2";
        hash = "sha256:1j22xbli4h2ni6y2a6ghfzdnwx0z5x1nw57hr6nmsdk0ys04a0gs";
      };
    };
    dune = 
    {
      pname = "dune";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = 
      {
        inherit (selection) base-unix
        base-threads;
        ocamlfind-secondary = selection.ocamlfind-secondary or null;
        ocaml = selection.ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune/dune.3.14.2";
        hash = "sha256:04m2slbrrz471qfi1zds89k02q0a4ka6jsas5prw8bjh2yn77g3h";
      };
    };
    dune-configurator = 
    {
      pname = "dune-configurator";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune csexp base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-configurator/dune-configurator.3.14.2";
        hash = "sha256:06hqqcs8xvzicmvnll8bzm4ww4k2d7hcxdjs6hc3ki7495cx978q";
      };
    };
    fmt = 
    {
      pname = "fmt";
      version = "0.9.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/fmt/releases/fmt-0.9.0.tbz";
        sha256 = "0q8j2in2473xh7k4hfgnppv9qy77f2ih89yp6yhpbp92ba021yzi";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
        base-unix = selection.base-unix or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fmt/fmt.0.9.0";
        hash = "sha256:1czh5i3i4mkf9xfasji3v7n821qmnnandlklh67ali0x87brldny";
      };
    };
    fpath = 
    {
      pname = "fpath";
      version = "0.7.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/fpath/releases/fpath-0.7.3.tbz";
        sha256 = "03z7mj0sqdz465rc4drj1gr88l9q3nfs374yssvdjdyhjbqqzc0j";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fpath/fpath.0.7.3";
        hash = "sha256:1pnskgw9fqq4kg1x4sc4vcv9rh0kksilx4qngwafpyss42mqq2i2";
      };
    };
    gen = 
    {
      pname = "gen";
      version = "1.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/c-cube/gen/archive/v1.1.tar.gz";
        sha256 = "1c4wz37k0fgyp3687kf5bcwz4c4hagzaabpcqm72b95sdcavz4v8";
      };
      opamInputs = {
                     inherit (selection) seq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/gen/gen.1.1";
        hash = "sha256:1kpxmk2ih8gnhcll0h4y2fm0ikr5bc3nhzbqxaqf0yfg1a75k3a3";
      };
    };
    jane-street-headers = 
    {
      pname = "jane-street-headers";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/jane-street-headers-v0.16.0.tar.gz";
        sha256 = "1sk0scvi657c0jvmdcgi2nmd4aa8qq0vc3q121xli5dlxsgl0vc7";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jane-street-headers/jane-street-headers.v0.16.0";
        hash = "sha256:04clgm4x0zbk9v5vs1v068i8ww48q91g1wa2kqxv0i63hawqc8i7";
      };
    };
    js_of_ocaml = 
    {
      pname = "js_of_ocaml";
      version = "5.7.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/js_of_ocaml/releases/download/5.7.1/js_of_ocaml-5.7.1.tbz";
        sha256 = "0g9q21rggn4ggdifinhlfl74xdblyqzhkyi5y9icaklhm0m8x90f";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml js_of_ocaml-compiler dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/js_of_ocaml/js_of_ocaml.5.7.1";
        hash = "sha256:0zsf9iw8sg6dw64blxjvxskzpy2h23b2340w0wf9dykqa4kjws9z";
      };
    };
    js_of_ocaml-compiler = 
    {
      pname = "js_of_ocaml-compiler";
      version = "5.7.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/js_of_ocaml/releases/download/5.7.1/js_of_ocaml-5.7.1.tbz";
        sha256 = "0g9q21rggn4ggdifinhlfl74xdblyqzhkyi5y9icaklhm0m8x90f";
      };
      opamInputs = 
      {
        inherit (selection) yojson sedlex ppxlib ocaml menhirSdk menhirLib
        menhir dune cmdliner;
        ocamlfind = selection.ocamlfind or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/js_of_ocaml-compiler/js_of_ocaml-compiler.5.7.1";
        hash = "sha256:1znkkiznf5mykcm4wvlfgnrh8h94r758imv9zp3d503gbxm821p2";
      };
    };
    js_of_ocaml-lwt = 
    {
      pname = "js_of_ocaml-lwt";
      version = "5.7.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/js_of_ocaml/releases/download/5.7.1/js_of_ocaml-5.7.1.tbz";
        sha256 = "0g9q21rggn4ggdifinhlfl74xdblyqzhkyi5y9icaklhm0m8x90f";
      };
      opamInputs = 
      {
        inherit (selection) ocaml lwt js_of_ocaml-ppx js_of_ocaml
        dune;
        lwt_log = selection.lwt_log or null;
        graphics = selection.graphics or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/js_of_ocaml-lwt/js_of_ocaml-lwt.5.7.1";
        hash = "sha256:0n7ihi5x3nwhfks78ykk7y1qphbjlkafyrv6331lmyix7yhs2h31";
      };
    };
    js_of_ocaml-ppx = 
    {
      pname = "js_of_ocaml-ppx";
      version = "5.7.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/js_of_ocaml/releases/download/5.7.1/js_of_ocaml-5.7.1.tbz";
        sha256 = "0g9q21rggn4ggdifinhlfl74xdblyqzhkyi5y9icaklhm0m8x90f";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml js_of_ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/js_of_ocaml-ppx/js_of_ocaml-ppx.5.7.1";
        hash = "sha256:04k72k3qv9jxyfdyg7hqkbbyzz1839cnrr7pyxk4z6hhgsij3md5";
      };
    };
    jst-config = 
    {
      pname = "jst-config";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/jst-config-v0.16.0.tar.gz";
        sha256 = "0nyr2hyff4s0qq66095p223w9705msdlzmcs17f8r1l2hmnxbsps";
      };
      opamInputs = 
      {
        inherit (selection) ppx_assert ocaml dune-configurator dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jst-config/jst-config.v0.16.0";
        hash = "sha256:1yvn8w6cx3xlx9aiy8zsqg26v59kcdq019lsgz9ybyhn6bj3fjpd";
      };
    };
    logs = 
    {
      pname = "logs";
      version = "0.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/logs/releases/logs-0.7.0.tbz";
        sha256 = "1jnmd675wmsmdwyb5mx5b0ac66g4c6gpv5s4mrx2j6pb0wla1x46";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        lwt = selection.lwt or null;
        js_of_ocaml = selection.js_of_ocaml or null;
        fmt = selection.fmt or null;
        cmdliner = selection.cmdliner or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/logs/logs.0.7.0";
        hash = "sha256:0pys6d25bghrwvwd4gflib2yyp5fvdy0rkivbdyli5dmp5j35a3n";
      };
    };
    lwt = 
    {
      pname = "lwt";
      version = "5.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/refs/tags/5.7.0.tar.gz";
        sha256 = "11dpr0aprqqjgb2n4j4czpw3l0bc8dzy1jqmp2qz3xkih31k241p";
      };
      opamInputs = 
      {
        inherit (selection) ocplib-endian ocaml dune-configurator dune
        cppo;
        conf-libev = selection.conf-libev or null;
        base-unix = selection.base-unix or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt/lwt.5.7.0";
        hash = "sha256:1fpvcmvrkwaz6w5rshgpw37n10dz9js68i553mmjs1g2g6wdpq73";
      };
    };
    lwt_ppx = 
    {
      pname = "lwt_ppx";
      version = "2.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/5.6.0.tar.gz";
        sha256 = "1qg5wjlmrnd295lljncr1db1rw50pr13wmak3rcg92n9wd1fzm0v";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml lwt dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt_ppx/lwt_ppx.2.1.0";
        hash = "sha256:09kc2bwmqq41983xivild7az3s62nrhp62iinvc2b6lpcldzvqqc";
      };
    };
    menhir = 
    {
      pname = "menhir";
      version = "20231231";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20231231/archive.tar.gz";
        sha256 = "1xn7760ahcf22y2ix597dh1wj7bc70x7fzj4vj73wch77imraffz";
      };
      opamInputs = 
      {
        inherit (selection) ocaml menhirSdk menhirLib menhirCST dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhir/menhir.20231231";
        hash = "sha256:0lpg8bv5ap8ydw4c2jf9zwq6b98fxh1flcj2y0dsp2qksg8y2bcz";
      };
    };
    menhirCST = 
    {
      pname = "menhirCST";
      version = "20231231";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20231231/archive.tar.gz";
        sha256 = "1xn7760ahcf22y2ix597dh1wj7bc70x7fzj4vj73wch77imraffz";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhirCST/menhirCST.20231231";
        hash = "sha256:0khjl269aln1nmbs57ff3gll328m01v5a3vvpxd0qqv3bbifbqdq";
      };
    };
    menhirLib = 
    {
      pname = "menhirLib";
      version = "20231231";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20231231/archive.tar.gz";
        sha256 = "1xn7760ahcf22y2ix597dh1wj7bc70x7fzj4vj73wch77imraffz";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhirLib/menhirLib.20231231";
        hash = "sha256:0f8hdphbih18p8a56a14fv22li9km7lik3np3l6skgkb2bsajbr3";
      };
    };
    menhirSdk = 
    {
      pname = "menhirSdk";
      version = "20231231";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20231231/archive.tar.gz";
        sha256 = "1xn7760ahcf22y2ix597dh1wj7bc70x7fzj4vj73wch77imraffz";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhirSdk/menhirSdk.20231231";
        hash = "sha256:0n2xvwz875fv8cm8ln2bljf5hb5xj2amjwgacz67dlgx100qx3ws";
      };
    };
    num = 
    {
      pname = "num";
      version = "1.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/num/archive/v1.5.tar.gz";
        sha256 = "16lm2l2j7wmxsz2nb4x1jvjjm48r4ypxqqla032xzqh1as7prq3s";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/num/num.1.5";
        hash = "sha256:06zrv1r5qn3hl9mpbhkbfckhhk6kysnkl348drvj3dmcg89hgnp8";
      };
    };
    ocaml = 
    {
      pname = "ocaml";
      version = "4.14.1";
      src = null;
      opamInputs = 
      {
        inherit (selection)
        ocaml-config;
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml/ocaml.4.14.1";
        hash = "sha256:16yvyr4nxcpvqp8w7wfhh9rkg2hl4ck3f64fw8kkgx7w2crcp8di";
      };
    };
    ocaml-base-compiler = 
    {
      pname = "ocaml-base-compiler";
      version = "4.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml/archive/4.14.1.tar.gz";
        sha256 = "0a5h8m8jliw0pf9xwbsnhp534x2qirc1qf3lkmnzpg5ry3k0cq3p";
      };
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-base-compiler/ocaml-base-compiler.4.14.1";
        hash = "sha256:1kpxp8pd4qw0imw3yxqk2m7fchb12b90nxgmqafha8f77qg6a0jw";
      };
    };
    ocaml-compiler-libs = 
    {
      pname = "ocaml-compiler-libs";
      version = "v0.12.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ocaml-compiler-libs/releases/download/v0.12.4/ocaml-compiler-libs-v0.12.4.tbz";
        sha256 = "0q3pl20pkx410gw9g4m26qq6dmzi9qan2dqlga6c2ifc6pnckjaf";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-compiler-libs/ocaml-compiler-libs.v0.12.4";
        hash = "sha256:1rn7ai9n2g5xja553qa5r9iamsqmrsnl4h7zkmmbcn27qj7vczsv";
      };
    };
    ocaml-config = 
    {
      pname = "ocaml-config";
      version = "2";
      src = null;
      opamInputs = 
      {
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-config/ocaml-config.2";
        hash = "sha256:0h0hgqq9mbywvqygppfdc50gf9ss8a97l4dgsv3hszmzh6gglgrg";
      };
    };
    ocamlbuild = 
    {
      pname = "ocamlbuild";
      version = "0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocamlbuild/archive/refs/tags/0.14.3.tar.gz";
        sha256 = "1qf21zds8f3izbb9bxwblijgb7wqkrhbl99z1gpcdas147yin5ff";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlbuild/ocamlbuild.0.14.3";
        hash = "sha256:0ymzb8ykkbvpzp8swdssr1iw85a0i66vprnxsxy6dpghhpm1rrqs";
      };
    };
    ocamlfind = 
    {
      pname = "ocamlfind";
      version = "1.9.6";
      src = pkgs.fetchurl 
      {
        url = "http://download.camlcity.org/download/findlib-1.9.6.tar.gz";
        sha256 = "18ih56m5z13z5zla7wdrin4y1bdz7pwpjn7znmnn0sz1k8krdy9d";
      };
      opamInputs = 
      {
        inherit (selection) ocaml;
        graphics = selection.graphics or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlfind/ocamlfind.1.9.6";
        hash = "sha256:1qs30vvj6mbrrgaxy54kw8zqqghxaywygyhspzhpdkwkl98j3y76";
      };
    };
    ocplib-endian = 
    {
      pname = "ocplib-endian";
      version = "1.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/OCamlPro/ocplib-endian/archive/refs/tags/1.2.tar.gz";
        sha256 = "085kskr0cxcnv2d62n3jq1r273p7giisy56zfl26mm7amvl79blp";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cppo base-bytes;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocplib-endian/ocplib-endian.1.2";
        hash = "sha256:1jldvb471gyhkrzwfvqg722l3a8dc37hhhyas66skjzfmqyi2pnh";
      };
    };
    odoc = 
    {
      pname = "odoc";
      version = "2.4.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/odoc/releases/download/2.4.1/odoc-2.4.1.tbz";
        sha256 = "1nyfb1si6fvrzfjxyz6wihyvclnhd6lxkl8pgyv3wl0b0aws055q";
      };
      opamInputs = 
      {
        inherit (selection) tyxml result odoc-parser ocaml fpath fmt dune
        crunch cppo cmdliner astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/odoc/odoc.2.4.1";
        hash = "sha256:1k250r12123a3cd5h8gjby6s8c77izdsc7wvhn3p7i7yyc3n819a";
      };
    };
    odoc-parser = 
    {
      pname = "odoc-parser";
      version = "2.4.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/odoc/releases/download/2.4.1/odoc-2.4.1.tbz";
        sha256 = "1nyfb1si6fvrzfjxyz6wihyvclnhd6lxkl8pgyv3wl0b0aws055q";
      };
      opamInputs = 
      {
        inherit (selection) result ocaml dune camlp-streams astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/odoc-parser/odoc-parser.2.4.1";
        hash = "sha256:07jngh0dg34fjdrlv3s9xfr43z1n7jykcwz31s5s4fh9y62ycg3j";
      };
    };
    parsexp = 
    {
      pname = "parsexp";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/parsexp-v0.16.0.tar.gz";
        sha256 = "04jywn2q3c4z2xla59qvr0i0bq3zv1p2ghzrp1fai4b1iqn5gqmn";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/parsexp/parsexp.v0.16.0";
        hash = "sha256:0rmgxgyd9s1600936l50a1b7xy64yhwk0jjzglzmpvikw2q9dl2x";
      };
    };
    ppx_assert = 
    {
      pname = "ppx_assert";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_assert-v0.16.0.tar.gz";
        sha256 = "1m9zi1ljdv31afgmi7cfbbgsvl6xhbvg4n69298ivsr730j6xp2p";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_here ppx_compare
        ppx_cold ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_assert/ppx_assert.v0.16.0";
        hash = "sha256:06mgc0vf5xxzpavrwfimy4m4hn22pil0nbvabz1q0wbhzslb2n70";
      };
    };
    ppx_base = 
    {
      pname = "ppx_base";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_base-v0.16.0.tar.gz";
        sha256 = "18v9jlykzf9vmf4c817mxl6d3gqy6mx31ksnzai64cix2mimg0v4";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_hash ppx_globalize
        ppx_enumerate ppx_compare ppx_cold ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_base/ppx_base.v0.16.0";
        hash = "sha256:1g513s531vrrvz4s3cnivrxl5zyl1b848m1v0dpdqd3d795hk7sf";
      };
    };
    ppx_cold = 
    {
      pname = "ppx_cold";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_cold-v0.16.0.tar.gz";
        sha256 = "1nm4d8p26mg3yf9vaaw5jspdi4mq2q6bwd5fv13a46jh7dcdnfw0";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_cold/ppx_cold.v0.16.0";
        hash = "sha256:1p8gk7scm9rxlxkwkksqnvkpjgva7l9pnn4k6bdpwpdlzjr7qgwa";
      };
    };
    ppx_compare = 
    {
      pname = "ppx_compare";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_compare-v0.16.0.tar.gz";
        sha256 = "1ai6iz2g8sla5jbqr7n34aw7s5n0cbcqp6w7d95nrpk25s2xvhbs";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_compare/ppx_compare.v0.16.0";
        hash = "sha256:0fd2c5xg9l531zbr0d90z8sl51zqpxjbgdv645zzvnvx5nkyca6w";
      };
    };
    ppx_derivers = 
    {
      pname = "ppx_derivers";
      version = "1.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz";
        sha256 = "159vqy616ni18mn0dlv8c2y4h7mb4hahwjn53yrr59yyhzhmwndn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_derivers/ppx_derivers.1.2.1";
        hash = "sha256:1hj1ina0n7pgz16mrvijczapw75pd0hif0i18dpw7d1fyg2qr8py";
      };
    };
    ppx_enumerate = 
    {
      pname = "ppx_enumerate";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_enumerate-v0.16.0.tar.gz";
        sha256 = "0lwrxx02shaskn810qba4a7592nd8lkxflgd90ywdi4sdmfn6ci8";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_enumerate/ppx_enumerate.v0.16.0";
        hash = "sha256:1305lmn66s3ncslsnjswhnc08gs979zh6j62znb78sx99p0af3gk";
      };
    };
    ppx_globalize = 
    {
      pname = "ppx_globalize";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_globalize-v0.16.0.tar.gz";
        sha256 = "06s9mfcknbjvsjfgklhizd508zq0vz559lvxn5s2j4b5nysdfs4h";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_globalize/ppx_globalize.v0.16.0";
        hash = "sha256:0s8z4i3cmzcj01amvc1y5q4zd0fy1r46zl20gk8k38by9jvwcy5f";
      };
    };
    ppx_hash = 
    {
      pname = "ppx_hash";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_hash-v0.16.0.tar.gz";
        sha256 = "1rdn2fzsqjdzx53smn20afxix8c8vav2z03gagyqn9xrnx32a0cv";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_compare ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_hash/ppx_hash.v0.16.0";
        hash = "sha256:0fnqs0xg08r3g9gx9g90gxqxzgncv2383659xdw54dbs604ks6pc";
      };
    };
    ppx_here = 
    {
      pname = "ppx_here";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_here-v0.16.0.tar.gz";
        sha256 = "1w3kjbnp16ypipfracpb0gr7imk4wbnks7j1ngx0dhq04nwri097";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_here/ppx_here.v0.16.0";
        hash = "sha256:044jv9sjivymm51lrg1p3hnnkp0rhjvi492jqviagarhimwmxlb2";
      };
    };
    ppx_inline_test = 
    {
      pname = "ppx_inline_test";
      version = "v0.16.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_inline_test/archive/refs/tags/v0.16.1.tar.gz";
        sha256 = "0p99wi0vrk1kn62a0i0qw7gj3bwfw51gclj7j1s6gmr90pjn2kpa";
      };
      opamInputs = 
      {
        inherit (selection) time_now ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_inline_test/ppx_inline_test.v0.16.1";
        hash = "sha256:00w5ndn3cbc3ma4k3c24lk596ds64ykk9jm9phzfwqfjsw97vbr1";
      };
    };
    ppx_optcomp = 
    {
      pname = "ppx_optcomp";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_optcomp-v0.16.0.tar.gz";
        sha256 = "18hbb7nmvrlnsmr6i2l9pyv2mav1jsbjicf6wkydlxak9840kclr";
      };
      opamInputs = 
      {
        inherit (selection) stdio ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_optcomp/ppx_optcomp.v0.16.0";
        hash = "sha256:1yx4r9qhbzm1rx5r9w1490p83z4n1hfjbqg3nnp249g9n83x218w";
      };
    };
    ppx_sexp_conv = 
    {
      pname = "ppx_sexp_conv";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_sexp_conv-v0.16.0.tar.gz";
        sha256 = "0390j76ins0hwxn4735ci2j2irgdphfszgq8hi151prvnfivgg21";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_sexp_conv/ppx_sexp_conv.v0.16.0";
        hash = "sha256:14ldpz4hcqbssgcy38h2i2fghw2f2y0m94fb5rjqzsmfy4n2v4yi";
      };
    };
    ppxlib = 
    {
      pname = "ppxlib";
      version = "0.32.1-5.2preview";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppxlib/archive/d7c5971884a9f4659daf87f3cab992fe5cbdc9fe.tar.gz";
        sha256 = "1aad0np59lgiqd82zl2ja6h0m6crbis7yrkd9dx66hcqha0cyii5";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims sexplib0 ppx_derivers
        ocaml-compiler-libs ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppxlib/ppxlib.0.32.1~5.2preview";
        hash = "sha256:1g65l2cdkd11f9q0bvia8l08i8wjpnh6a9khcwwkbszlmna350wi";
      };
    };
    ptime = 
    {
      pname = "ptime";
      version = "1.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/ptime/releases/ptime-1.1.0.tbz";
        sha256 = "1c9y07vnvllfprf0z1vqf6fr73qxw7hj6h1k5ig109zvaiab3xfb";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ptime/ptime.1.1.0";
        hash = "sha256:0a6ga17zw5h31107bc47r37mr31dwxnji1c39xx558w39c1avp7p";
      };
    };
    re = 
    {
      pname = "re";
      version = "1.11.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml-re/releases/download/1.11.0/re-1.11.0.tbz";
        sha256 = "0kwdvzb2wy3rxq3mvmsgc8cdwrzka2viysvrmrrbxxn0h13j9z01";
      };
      opamInputs = {
                     inherit (selection) seq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/re/re.1.11.0";
        hash = "sha256:18048c9lw3g8db1r01diljzvla2pj9bw2fcnvq34gnviwi9rxqjf";
      };
    };
    result = 
    {
      pname = "result";
      version = "1.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/result/releases/download/1.5/result-1.5.tbz";
        sha256 = "0cpfp35fdwnv3p30a06wd0py3805qxmq3jmcynjc3x2qhlimwfkw";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/result/result.1.5";
        hash = "sha256:0ybmvlisfz5swvbcq855czz1ysv9zxmb79f1m0x8284hczmfm98f";
      };
    };
    sedlex = 
    {
      pname = "sedlex";
      version = "3.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/sedlex/archive/refs/tags/v3.2.tar.gz";
        sha256 = "179ycb36hz48h8cizq1l1m03cmirchv4hw4x3pg2rinphf9cij68";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml gen dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sedlex/sedlex.3.2";
        hash = "sha256:0dx4yr51v9kvf1yhjxjj81dj2hxwidmpa5z6g8srv32wm4i4wxl8";
      };
    };
    seq = 
    {
      pname = "seq";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/seq/seq.base";
        hash = "sha256:1vm8mk6zm2q3fwnkprl6jib048zr4ysldw0bl74x6wwbxj0vx6k9";
      };
    };
    sexplib = 
    {
      pname = "sexplib";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/sexplib-v0.16.0.tar.gz";
        sha256 = "0nxc47d9szcxs3vfqfzfxylcpihjza4lwjynbyx18wqmrb8xar75";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 parsexp ocaml num dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib/sexplib.v0.16.0";
        hash = "sha256:19x1c3s6nnj6vk3yil4a4vj8ylzv7v2nk89rpa344jjijq41cvj2";
      };
    };
    sexplib0 = 
    {
      pname = "sexplib0";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/sexplib0-v0.16.0.tar.gz";
        sha256 = "07bhj2akd6i33h11qin4wns9qnjicf871yzji7vi4i8rd1ja5nw6";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib0/sexplib0.v0.16.0";
        hash = "sha256:11zmpbm8pj86dmc2fgbz33ngqs1a854dgsayq24hzlvdvif5bgqw";
      };
    };
    stdio = 
    {
      pname = "stdio";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/stdio-v0.16.0.tar.gz";
        sha256 = "0gm7nci6bi3gfc5q3m8rv4138ip6rhidih3fihvwajk1a1cvgw31";
      };
      opamInputs = {
                     inherit (selection) ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdio/stdio.v0.16.0";
        hash = "sha256:029985vdqfj1xavwdrhd2kgs8pkfdfkf39bb90fb3ap180fqfw81";
      };
    };
    stdlib-shims = 
    {
      pname = "stdlib-shims";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz";
        sha256 = "0jnqsv6pqp5b5g7lcjwgd75zqqvcwcl5a32zi03zg1kvj79p5gxs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdlib-shims/stdlib-shims.0.3.0";
        hash = "sha256:1hwyzzcx7clz4p58fj3n6frq2srbxdmhmxxd6n6mpw9gj2vs6yiw";
      };
    };
    time_now = 
    {
      pname = "time_now";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/time_now-v0.16.0.tar.gz";
        sha256 = "18f3dpafs7pj07wnymyhrpp6kzhx1jya5r3ni6xyvap6vsm8982z";
      };
      opamInputs = 
      {
        inherit (selection) ppx_optcomp ppx_base ocaml jst-config
        jane-street-headers dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/time_now/time_now.v0.16.0";
        hash = "sha256:1znd8q9s42jsplz0xrlrvq838q0pia6qp6m5kj48gnsd22c1zfxd";
      };
    };
    topkg = 
    {
      pname = "topkg";
      version = "1.0.7";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/topkg/releases/topkg-1.0.7.tbz";
        sha256 = "06dya9n5im3dbqqv4l6yssi8siw111c1hp94n5y14vddyg9jmhjz";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/topkg/topkg.1.0.7";
        hash = "sha256:1411142m653308lj3nlgbv2wvww2i5hyfdgz94l2b3ga3qdp7szc";
      };
    };
    tyxml = 
    {
      pname = "tyxml";
      version = "4.6.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/tyxml/releases/download/4.6.0/tyxml-4.6.0.tbz";
        sha256 = "1p82r68lxk6wzxihzd620a6kzp27vn548j2cr970l4jfdcy6gsxz";
      };
      opamInputs = 
      {
        inherit (selection) uutf seq re ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/tyxml/tyxml.4.6.0";
        hash = "sha256:02pnpfr487d077arnvras1a6p52san6l5xkw0adgaxqpi7cf1cqy";
      };
    };
    uutf = 
    {
      pname = "uutf";
      version = "1.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uutf/releases/uutf-1.0.3.tbz";
        sha256 = "0s05r8ggp1g97zq4rnvbxzj22pv8ld0k5wsdw662jw0y7mhsawl7";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uutf/uutf.1.0.3";
        hash = "sha256:1x57h3bc68rsm2kd18wjbkfjk67shak6jgplp7paw97faqgmgx3x";
      };
    };
    vdoml = 
    {
      pname = "vdoml";
      version = "development";
      src = self.directSrc "vdoml";
      opamInputs = 
      {
        inherit (selection) odoc ocamlfind ocaml lwt_ppx lwt logs
        js_of_ocaml-ppx js_of_ocaml-lwt js_of_ocaml dune conf-python-3;
      };
      opamSrc = "vdoml.opam";
    };
    yojson = 
    {
      pname = "yojson";
      version = "2.1.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/yojson/releases/download/2.1.2/yojson-2.1.2.tbz";
        sha256 = "1ydlvw0f50vg8ia9529ldq07d2jyqzjr9230pyywr9y8pymz3wjr";
      };
      opamInputs = 
      {
        inherit (selection) seq ocaml dune cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/yojson/yojson.2.1.2";
        hash = "sha256:10cqyg4ykrfc39lfb0xhykknym1pz5saivq3ighgns4a1rnkixf3";
      };
    };
  };
}

