#!bash -eu
FLAGS=()
if test "${GUP_XTRACE:-0}" = 1; then
	set -x
	FLAGS+=(-verbose 3)
fi

if test "${OCAMLBUILD_FATAL_WARNINGS:-0}" = 1; then
	FLAGS+=(-cflag -warn-error -cflag A)
fi

basedir="${2%_build/*}"
target_name="${2#*_build/}"
if test -z "$basedir"; then
	basedir="."
fi
if [[ "$target_name" == *.docdir ]]; then
	# actually tell ocamlbuild to make */index.html,
	# because we can\'t store gup metadata in ocamlbuild's
	# owned docdir
	target_name="$target_name/index.html"
fi

# don't build anything without a _tags file
test -f "$basedir/_tags" || (echo "No tags file found in '$basedir'"; exit 1)
pushd "$basedir" >/dev/null
if [ "$(basename "$(dirname "$(pwd)")")" = 'examples' ]; then
	gup -u ../../lib
fi
ocamlbuild "${FLAGS[@]}" -use-ocamlfind -no-links "$target_name"
popd >/dev/null
gup --always
gup --leave
if ! [ -d "$2" ]; then
	gup --contents "$2"
fi
