#!/bin/bash
set -eu
if test "${GUP_XTRACE:-0}" -eq 1; then
	set -x
fi

# Build JS code from the OCaml bytecode
base="${2%.js}"
if [[ $2 == test/* ]]; then
	FLAGS="+weak.js test/stub.js"
else
	if [[ $base == *.min ]]; then
		base="${base%.min}"
		FLAGS="--opt 3"
	else
		FLAGS="--debug-info --source-map-inline --sourcemap"
	fi
fi
gup -u "$base.byte"
js_of_ocaml $FLAGS -o "$1" "$base.byte"
