#!bash -eu
OCAMLBUILD_FLAGS=""
if test "${GUP_XTRACE:-0}" -eq 1; then
	set -x
	OCAMLBUILD_FLAGS="-verbose 3"
fi

echo "$2"
basedir="${2%/_build/*}"
target_name="${2#*/_build/}"
# don't build anything without a _tags file
test -f "$basedir/_tags" || (echo "No tags file found in '$basedir'"; exit 1)
root="$(pwd)"
pushd "$basedir" >/dev/null
ocamlbuild $OCAMLBUILD_FLAGS -use-ocamlfind -no-links "$target_name"
popd >/dev/null
gup --always
gup --leave
gup --contents "$2"
